cc_test(
    name = "utility_test",
    size = "small",
    srcs = glob(["*.cpp"]),
    deps = [
        "//:riw_test_library",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)
